// <auto-generated />
using System;
using System.Collections.Generic;
using LogisticsDispatch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsDispatch.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    [Migration("20261009210956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LogisticsDispatch.Core.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CurrentLocation", "LogisticsDispatch.Core.Entities.Driver.CurrentLocation#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL");

                            b1.Property<double>("Lng")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("LogisticsDispatch.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AssignedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EtaSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CurrentLocation", "LogisticsDispatch.Core.Entities.Job.CurrentLocation#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL");

                            b1.Property<double>("Lng")
                                .HasColumnType("REAL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dropoff", "LogisticsDispatch.Core.Entities.Job.Dropoff#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL");

                            b1.Property<double>("Lng")
                                .HasColumnType("REAL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Pickup", "LogisticsDispatch.Core.Entities.Job.Pickup#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL");

                            b1.Property<double>("Lng")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("LogisticsDispatch.Core.Entities.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("LogisticsDispatch.Core.Entities.StatusHistory", b =>
                {
                    b.HasOne("LogisticsDispatch.Core.Entities.Job", null)
                        .WithMany("History")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDispatch.Core.Entities.Job", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
